export default (theme) => ({
  container: {
    display: 'flex',
    flexGrow: 1,
    flexDirection: 'column',
    alignItems: 'center',
    overflow: 'auto',
    paddingRight: theme.spacing * 2,
  },
  feed: {
    display: 'inline-flex',
    justifyContent: 'center',
    width: '100%',
    boxSizing: 'border-box',
    paddingTop: theme.spacing * 2,
  },
  select: {
    width: 200,
    backgroundColor: theme.colors.white,
  },
  empty: {
    display: 'flex',
    alignItems: 'center',
    ...theme.typography.h1,
    fontSize: 20,
    fontWeight: 300,
  },
  feed__column: {
    display: 'flex',
    flexDirection: 'column',
    height: 'auto',
    paddingLeft: theme.spacing * 2,
    paddingRight: theme.spacing * 2,
    width: `calc(100% - ${theme.spacing * 4}px)`,
    flexGrow: 1,
    marginBottom: theme.spacing * 2,
    maxWidth: 750,
  },
  feed__aside: {
    display: 'flex',
    flexDirection: 'column',
    height: 'auto',
    width: 300,
    flexShrink: 0,
  },
  header__spacer: {
    height: 48,
  },
  feed__header: {
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
    minHeight: 50,
    justifyContent: 'space-between',
    paddingBottom: theme.spacing * 0.5,
    borderBottom: '1px solid rgba(0, 0, 0, 0.1)',
    marginBottom: theme.spacing * 2,
    zIndex: 10,
  },
  header__title: {
    display: 'flex',
    alignItems: 'center',
    ...theme.typography.h1,
    fontSize: 14,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    color: 'rgba(53, 64, 82, 0.8)',
  },
  feed__list: {
    display: 'flex',
    flexDirection: 'column',
    height: 'auto',
    width: '100%',
  },
  featured__list: {
    height: 'auto',
    width: '100%',
  },
  featured__article: {
    display: 'block',
    marginBottom: theme.spacing * 1.5,
    textDecoration: 'none',
  },
  loader: {
    position: 'relative',
    backgroundColor: 'transparent',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 500,
    width: '100%',
  },
});
