export default (theme) => ({
  link: {
    textDecoration: 'none',
  },
  article: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    cursor: 'pointer',
    transition: 'transform 0.2s',
    '&:hover': {
      transform: 'scale(1.05)',
      borderRadius: theme.borderRadius,
      boxShadow: '0px 0px 25px #cfcfd1',
    },
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    height: 80,
    flexShrink: 0,
    paddingLeft: theme.spacing,
    paddingRight: theme.spacing,
    width: '100%',
    boxSizing: 'border-box',
  },
  figure: {
    margin: 0,
    height: 200,
    flexGrow: 1,
    textDecoration: 'none',
  },
  image: {
    height: '100%',
    width: '100%',
    objectFit: 'cover',
  },
  footer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    height: 100,
    flexShrink: 0,
    paddingLeft: theme.spacing,
    paddingRight: theme.spacing,
    width: `calc(100% - ${theme.spacing * 2}px)`,
  },
  title: {
    ...theme.typography.h6,
    fontWeight: 400,
    fontSize: 22,
    maxWidth: '100%',
    textDecoration: 'none',
    marginBottom: 0,
  },
  description: {
    ...theme.typography.help,
    fontWeight: 400,
    fontSize: 14,
    color: 'rgba(53, 64, 82, 0.6)',
    margin: '10px 0 0 0',
    maxWidth: '100%',
    marginTop: 0,
  },
  card: {
    backgroundColor: theme.colors.white,
    width: '100%',
    marginBottom: theme.spacing * 1.5,
    borderRadius: theme.borderRadius,
  },
  overflow: {
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
  },
});
