export default (theme) => ({
  container: {
    display: 'flex',
    flexDirection: 'row',
    position: 'relative',
    backgroundColor: theme.colors.white,
    height: 'auto',
    width: '100%',
    overflow: 'auto',
  },
  details: {
    position: 'sticky',
    top: 0,
    backgroundColor: theme.colors.white,
    padding: theme.spacing,
    boxShadow: theme.boxShadows.medium,
    zIndex: 10,
    width: 'auto',
    height: 40,
  },
  details__inner: {
    display: 'flex',
    alignItems: 'center',
  },
  header: {
    display: 'flex',
    flexShrink: 0,
    height: '37vh',
    backgroundColor: theme.colors.gray,
  },
  draft: {
    display: 'inline-flex',
    flexDirection: 'column',
    flexGrow: 1,
    minHeight: '50vh',
    height: '100%',
    maxWidth: 'calc(100% - 270px)',
  },
  main: {
    display: 'flex',
    flexDirection: 'column',
    flexShrink: 0,
    minHeight: '30vh',
    width: '100%',
    height: '100%',
  },
  title: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    minHeight: 65,
    borderBottom: '1px solid rgba(0, 0, 0, 0.1)',
    paddingLeft: theme.spacing,
    paddingRight: theme.spacing * 8,
    flexShrink: 0,
    borderRight: '1px solid rgba(0, 0, 0, 0.1)',
  },
  editor: {
    display: 'block',
    paddingLeft: 60,
    borderRight: '1px solid rgba(0, 0, 0, 0.1)',
    minHeight: '70vh',
    paddingTop: theme.spacing * 2,
  },
  aside: {
    display: 'flex',
    flexShrink: 0,
    flexDirection: 'column',
    paddingLeft: theme.spacing,
    paddingTop: theme.spacing * 2,
    paddingRight: theme.spacing,
    width: '25%',
    height: '100%',
  },
  footer: {
    display: 'flex',
    alignItems: 'center',
    paddingLeft: theme.spacing,
    minHeight: 60,
    borderTop: '1px solid rgba(0, 0, 0, 0.1)',
    backgroundColor: theme.colors.lightestGray,
    borderRight: '1px solid rgba(0, 0, 0, 0.1)',
  },
  block: {
    display: 'flex',
    flexDirection: 'column',
    padding: theme.spacing * 0.5,
    backgroundColor: theme.colors.white,
    marginBottom: theme.spacing,
    boxShadow: theme.boxShadows.small,
  },
});
