version: 2
jobs:
  build:
    working_directory: ~/lunyr-orbiter
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: sudo apt update

      - run: sudo apt -y install libgtk-3-0 libgtkextra-dev libgconf2-dev libnss3 libasound2 libxtst-dev libxss1

      - run: yarn install --production=false

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: xvfb-run yarn test test/**/*.js